// <auto-generated />
namespace AppiaryData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VirtualCollections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VirtualCollections));
        
        string IMigrationMetadata.Id
        {
            get { return "201610051717189_VirtualCollections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
